# Generated by Django 5.0.2 on 2024-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crews',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('directors', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('writers', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('parentTconst', models.CharField(default='\\N', max_length=255)),
                ('seasonNumber', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('episodeNumber', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('titleType', models.CharField(choices=[('short', 'short'), ('movie', 'movie'), ('tvEpisode', 'tvEpisode')], max_length=20)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('originalTitle', models.CharField(max_length=255)),
                ('isAdult', models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('startYear', models.CharField(max_length=255)),
                ('endYear', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('runtimeMinutes', models.PositiveIntegerField(blank=True, default='\\N', null=True)),
                ('genres', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('img_url_asset', models.URLField(blank=True, default='\\N', max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('nconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('primaryName', models.CharField(max_length=255)),
                ('birthYear', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('deathYear', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('primaryProfession', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('knownForTitles', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('img_url_asset', models.URLField(blank=True, default='\\N', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('tconst', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('averageRating', models.CharField(max_length=255)),
                ('numVotes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Akas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleId', models.CharField(max_length=255)),
                ('ordering', models.SmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('language', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('types', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('attributes', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('isOriginalTitle', models.BooleanField(choices=[(0, 'False'), (1, 'True')], default=0)),
            ],
            options={
                'unique_together': {('titleId', 'ordering')},
            },
        ),
        migrations.CreateModel(
            name='Principals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=255)),
                ('ordering', models.SmallIntegerField()),
                ('nconst', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('job', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('characters', models.CharField(blank=True, default='\\N', max_length=255, null=True)),
                ('img_url_asset', models.URLField(blank=True, default='\\N', max_length=2000, null=True)),
            ],
            options={
                'unique_together': {('tconst', 'ordering')},
            },
        ),
    ]
