# Generated by Django 5.0.1 on 2024-02-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Cli',
        ),
    ]
