# Generated by Django 5.0.1 on 2024-02-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0002_rename_member_cli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tconst', models.CharField(max_length=255)),
                ('titleType', models.CharField(max_length=255)),
                ('primaryTitle', models.CharField(max_length=255)),
                ('originalTitle', models.CharField(max_length=255)),
                ('isAdult', models.BooleanField()),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField(blank=True, null=True)),
                ('runtimeMinutes', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('img_url_asset', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
